import walk1_left from "../sprites/player/walk1_left.png";
import walk1_right from "../sprites/player/walk1_right.png";
import walk2_left from "../sprites/player/walk2_left.png";
import walk2_right from "../sprites/player/walk2_right.png";
import walk3_left from "../sprites/player/walk3_left.png";
import walk3_right from "../sprites/player/walk3_right.png";
import walk4_left from "../sprites/player/walk4_left.png";
import walk4_right from "../sprites/player/walk4_right.png";
import whip1_left from "../sprites/player/whip1_left.png";
import whip1_right from "../sprites/player/whip1_right.png";
import whip2_left from "../sprites/player/whip2_left.png";
import whip2_right from "../sprites/player/whip2_right.png";
import whip3_left from "../sprites/player/whip3_left.png";
import whip3_right from "../sprites/player/whip3_right.png";
import jump_left from "../sprites/player/jump_left.png";
import jump_right from "../sprites/player/jump_right.png";
import fall_left from "../sprites/player/fall_left.png";
import fall_right from "../sprites/player/fall_right.png";
import damage_left from "../sprites/player/damage_left.png";
import damage_right from "../sprites/player/damage_right.png";
import dead_left from "../sprites/player/dead_left.png";
import dead_right from "../sprites/player/dead_right.png";

import bg1 from "../sprites/environment/background-outside.png";
import moon from "../sprites/environment/moon-parallax.png";
import cloud1 from "../sprites/environment/cloud1.png";
import cloud2 from "../sprites/environment/cloud2.png";
import cloud3 from "../sprites/environment/cloud3.png";
import greenStoneTile from "../sprites/environment/green-stone-tile.png";

import skeleton1_left from "../sprites/skeleton/skeleton-clothed-1.png";
import skeleton1_right from "../sprites/skeleton/skeleton-clothed-1-flipped.png";
import skeleton2_left from "../sprites/skeleton/skeleton-clothed-2.png";
import skeleton2_right from "../sprites/skeleton/skeleton-clothed-2-flipped.png";
import skeleton3_left from "../sprites/skeleton/skeleton-clothed-3.png";
import skeleton3_right from "../sprites/skeleton/skeleton-clothed-3-flipped.png";
import skeleton4_left from "../sprites/skeleton/skeleton-clothed-4.png";
import skeleton4_right from "../sprites/skeleton/skeleton-clothed-4-flipped.png";
import skeleton5_left from "../sprites/skeleton/skeleton-clothed-5.png";
import skeleton5_right from "../sprites/skeleton/skeleton-clothed-5-flipped.png";
import skeleton6_left from "../sprites/skeleton/skeleton-clothed-6.png";
import skeleton6_right from "../sprites/skeleton/skeleton-clothed-6-flipped.png";
import skeleton7_left from "../sprites/skeleton/skeleton-clothed-7.png";
import skeleton7_right from "../sprites/skeleton/skeleton-clothed-7-flipped.png";
import skeleton8_left from "../sprites/skeleton/skeleton-clothed-8.png";
import skeleton8_right from "../sprites/skeleton/skeleton-clothed-8-flipped.png";

import skeleton_rise1_left from "../sprites/skeleton/skeleton-rise-clothed-1.png";
import skeleton_rise1_right from "../sprites/skeleton/skeleton-rise-clothed-1-flipped.png";
import skeleton_rise2_left from "../sprites/skeleton/skeleton-rise-clothed-2.png";
import skeleton_rise2_right from "../sprites/skeleton/skeleton-rise-clothed-2-flipped.png";
import skeleton_rise3_left from "../sprites/skeleton/skeleton-rise-clothed-3.png";
import skeleton_rise3_right from "../sprites/skeleton/skeleton-rise-clothed-3-flipped.png";
import skeleton_rise4_left from "../sprites/skeleton/skeleton-rise-clothed-4.png";
import skeleton_rise4_right from "../sprites/skeleton/skeleton-rise-clothed-4-flipped.png";
import skeleton_rise5_left from "../sprites/skeleton/skeleton-rise-clothed-5.png";
import skeleton_rise5_right from "../sprites/skeleton/skeleton-rise-clothed-5-flipped.png";
import skeleton_rise6_left from "../sprites/skeleton/skeleton-rise-clothed-6.png";
import skeleton_rise6_right from "../sprites/skeleton/skeleton-rise-clothed-6-flipped.png";

import enemy_death1 from "../sprites/enemy-death/enemy-death-1.png";
import enemy_death2 from "../sprites/enemy-death/enemy-death-2.png";
import enemy_death3 from "../sprites/enemy-death/enemy-death-3.png";
import enemy_death4 from "../sprites/enemy-death/enemy-death-4.png";
import enemy_death5 from "../sprites/enemy-death/enemy-death-5.png";

import ghost1_right from "../sprites/ghost/ghost-1.png";
import ghost1_left from "../sprites/ghost/ghost-1-flipped.png";
import ghost2_right from "../sprites/ghost/ghost-2.png";
import ghost2_left from "../sprites/ghost/ghost-2-flipped.png";
import ghost3_right from "../sprites/ghost/ghost-3.png";
import ghost3_left from "../sprites/ghost/ghost-3-flipped.png";
import ghost4_right from "../sprites/ghost/ghost-4.png";
import ghost4_left from "../sprites/ghost/ghost-4-flipped.png";

const walk1LeftImg = new Image();
walk1LeftImg.src = walk1_left;
const walk1RightImg = new Image();
walk1RightImg.src = walk1_right;
const walk2LeftImg = new Image();
walk2LeftImg.src = walk2_left;
const walk2RightImg = new Image();
walk2RightImg.src = walk2_right;
const walk3LeftImg = new Image();
walk3LeftImg.src = walk3_left;
const walk3RightImg = new Image();
walk3RightImg.src = walk3_right;
const walk4LeftImg = new Image();
walk4LeftImg.src = walk4_left;
const walk4RightImg = new Image();
walk4RightImg.src = walk4_right;
const whip1LeftImg = new Image();
whip1LeftImg.src = whip1_left;
const whip1RightImg = new Image();
whip1RightImg.src = whip1_right;
const whip2LeftImg = new Image();
whip2LeftImg.src = whip2_left;
const whip2RightImg = new Image();
whip2RightImg.src = whip2_right;
const whip3LeftImg = new Image();
whip3LeftImg.src = whip3_left;
const whip3RightImg = new Image();
whip3RightImg.src = whip3_right;
const jumpLeftImg = new Image();
jumpLeftImg.src = jump_left;
const jumpRightImg = new Image();
jumpRightImg.src = jump_right;
const fallLeftImg = new Image();
fallLeftImg.src = fall_left;
const fallRightImg = new Image();
fallRightImg.src = fall_right;
const damageLeftImg = new Image();
damageLeftImg.src = damage_left;
const damageRightImg = new Image();
damageRightImg.src = damage_right;
const deadLeftImg = new Image();
deadLeftImg.src = dead_left;
const deadRightImg = new Image();
deadRightImg.src = dead_right;

const bg1Img = new Image();
bg1Img.src = bg1;
const moonImg = new Image();
moonImg.src = moon;
const cloud1Img = new Image();
cloud1Img.src = cloud1;
const cloud2Img = new Image();
cloud2Img.src = cloud2;
const cloud3Img = new Image();
cloud3Img.src = cloud3;
const greenStoneTileImg = new Image();
greenStoneTileImg.src = greenStoneTile;

const skeleton1Left = new Image();
skeleton1Left.src = skeleton1_left;
const skeleton2Left = new Image();
skeleton2Left.src = skeleton2_left;
const skeleton3Left = new Image();
skeleton3Left.src = skeleton3_left;
const skeleton4Left = new Image();
skeleton4Left.src = skeleton4_left;
const skeleton5Left = new Image();
skeleton5Left.src = skeleton5_left;
const skeleton6Left = new Image();
skeleton6Left.src = skeleton6_left;
const skeleton7Left = new Image();
skeleton7Left.src = skeleton7_left;
const skeleton8Left = new Image();
skeleton8Left.src = skeleton8_left;
const skeleton1Right = new Image();
skeleton1Right.src = skeleton1_right;
const skeleton2Right = new Image();
skeleton2Right.src = skeleton2_right;
const skeleton3Right = new Image();
skeleton3Right.src = skeleton3_right;
const skeleton4Right = new Image();
skeleton4Right.src = skeleton4_right;
const skeleton5Right = new Image();
skeleton5Right.src = skeleton5_right;
const skeleton6Right = new Image();
skeleton6Right.src = skeleton6_right;
const skeleton7Right = new Image();
skeleton7Right.src = skeleton7_right;
const skeleton8Right = new Image();
skeleton8Right.src = skeleton8_right;

const skeletonRise1Left = new Image();
skeletonRise1Left.src = skeleton_rise1_left;
const skeletonRise2Left = new Image();
skeletonRise2Left.src = skeleton_rise2_left;
const skeletonRise3Left = new Image();
skeletonRise3Left.src = skeleton_rise3_left;
const skeletonRise4Left = new Image();
skeletonRise4Left.src = skeleton_rise4_left;
const skeletonRise5Left = new Image();
skeletonRise5Left.src = skeleton_rise5_left;
const skeletonRise6Left = new Image();
skeletonRise6Left.src = skeleton_rise6_left;
const skeletonRise1Right = new Image();
skeletonRise1Right.src = skeleton_rise1_right;
const skeletonRise2Right = new Image();
skeletonRise2Right.src = skeleton_rise2_right;
const skeletonRise3Right = new Image();
skeletonRise3Right.src = skeleton_rise3_right;
const skeletonRise4Right = new Image();
skeletonRise4Right.src = skeleton_rise4_right;
const skeletonRise5Right = new Image();
skeletonRise5Right.src = skeleton_rise5_right;
const skeletonRise6Right = new Image();
skeletonRise6Right.src = skeleton_rise6_right;

const enemyDeath1 = new Image();
enemyDeath1.src = enemy_death1;
const enemyDeath2 = new Image();
enemyDeath2.src = enemy_death2;
const enemyDeath3 = new Image();
enemyDeath3.src = enemy_death3;
const enemyDeath4 = new Image();
enemyDeath4.src = enemy_death4;
const enemyDeath5 = new Image();
enemyDeath5.src = enemy_death5;

const ghost1Left = new Image();
ghost1Left.src = ghost1_left;
const ghost2Left = new Image();
ghost2Left.src = ghost2_left;
const ghost3Left = new Image();
ghost3Left.src = ghost3_left;
const ghost4Left = new Image();
ghost4Left.src = ghost4_left;
const ghost1Right = new Image();
ghost1Right.src = ghost1_right;
const ghost2Right = new Image();
ghost2Right.src = ghost2_right;
const ghost3Right = new Image();
ghost3Right.src = ghost3_right;
const ghost4Right = new Image();
ghost4Right.src = ghost4_right;

export const characterIdleLeft = [walk1LeftImg];
export const characterIdleRight = [walk1RightImg];
export const characterWalkingLeft = [walk1LeftImg, walk2LeftImg, walk3LeftImg, walk4LeftImg];
export const characterWalkingRight = [walk1RightImg, walk2RightImg, walk3RightImg, walk4RightImg];
export const characterWhipLeft = [whip1LeftImg, whip2LeftImg, whip3LeftImg];
export const characterWhipRight = [whip1RightImg, whip2RightImg, whip3RightImg];
export const characterJumpLeft = [jumpLeftImg];
export const characterJumpRight = [jumpRightImg];
export const characterFallLeft = [fallLeftImg];
export const characterFallRight = [fallRightImg];
export const characterDamageLeft = [damageLeftImg];
export const characterDamageRight = [damageRightImg];
export const characterDeadLeft = [deadLeftImg];
export const characterDeadRight = [deadRightImg];

export const environmentImgs = [greenStoneTileImg];
export const bgImgs = [bg1Img];
export const bgParallaxImgs = [moonImg, cloud1Img, cloud2Img, cloud3Img];

export const zombieLeft = [skeleton1Left, skeleton2Left, skeleton3Left, skeleton4Left, skeleton5Left, skeleton6Left, skeleton7Left, skeleton8Left];
export const zombieRight = [skeleton1Right, skeleton2Right, skeleton3Right, skeleton4Right, skeleton5Right, skeleton6Right, skeleton7Right, skeleton8Right];
export const zombieRiseLeft = [skeletonRise1Left, skeletonRise2Left, skeletonRise3Left, skeletonRise4Left, skeletonRise5Left, skeletonRise6Left];
export const zombieRiseRight = [skeletonRise1Right, skeletonRise2Right, skeletonRise3Right, skeletonRise4Right, skeletonRise5Right, skeletonRise6Right];

export const enemyDeath = [enemyDeath1, enemyDeath2, enemyDeath3, enemyDeath4, enemyDeath5];

export const ghostRight = [ghost1Right, ghost2Right, ghost3Right, ghost4Right];
export const ghostLeft = [ghost1Left, ghost2Left, ghost3Left, ghost4Left];
