import walk1_left from "../sprites/player/walk1_left.png";
import walk1_right from "../sprites/player/walk1_right.png";
import walk2_left from "../sprites/player/walk2_left.png";
import walk2_right from "../sprites/player/walk2_right.png";
import walk3_left from "../sprites/player/walk3_left.png";
import walk3_right from "../sprites/player/walk3_right.png";
import walk4_left from "../sprites/player/walk4_left.png";
import walk4_right from "../sprites/player/walk4_right.png";
import whip1_left from "../sprites/player/whip1_left.png";
import whip1_right from "../sprites/player/whip1_right.png";
import whip2_left from "../sprites/player/whip2_left.png";
import whip2_right from "../sprites/player/whip2_right.png";
import whip3_left from "../sprites/player/whip3_left.png";
import whip3_right from "../sprites/player/whip3_right.png";
import jump_left from "../sprites/player/jump_left.png";
import jump_right from "../sprites/player/jump_right.png";
import fall_left from "../sprites/player/fall_left.png";
import fall_right from "../sprites/player/fall_right.png";
import damage_left from "../sprites/player/damage_left.png";
import damage_right from "../sprites/player/damage_right.png";
import dead_left from "../sprites/player/dead_left.png";
import dead_right from "../sprites/player/dead_right.png";

import bg1 from "../sprites/environment/background-outside.png";
import greenStoneTile from "../sprites/environment/green-stone-tile.png";

const walk1LeftImg = new Image();
walk1LeftImg.src = walk1_left;
const walk1RightImg = new Image();
walk1RightImg.src = walk1_right;
const walk2LeftImg = new Image();
walk2LeftImg.src = walk2_left;
const walk2RightImg = new Image();
walk2RightImg.src = walk2_right;
const walk3LeftImg = new Image();
walk3LeftImg.src = walk3_left;
const walk3RightImg = new Image();
walk3RightImg.src = walk3_right;
const walk4LeftImg = new Image();
walk4LeftImg.src = walk4_left;
const walk4RightImg = new Image();
walk4RightImg.src = walk4_right;
const whip1LeftImg = new Image();
whip1LeftImg.src = whip1_left;
const whip1RightImg = new Image();
whip1RightImg.src = whip1_right;
const whip2LeftImg = new Image();
whip2LeftImg.src = whip2_left;
const whip2RightImg = new Image();
whip2RightImg.src = whip2_right;
const whip3LeftImg = new Image();
whip3LeftImg.src = whip3_left;
const whip3RightImg = new Image();
whip3RightImg.src = whip3_right;
const jumpLeftImg = new Image();
jumpLeftImg.src = jump_left;
const jumpRightImg = new Image();
jumpRightImg.src = jump_right;
const fallLeftImg = new Image();
fallLeftImg.src = fall_left;
const fallRightImg = new Image();
fallRightImg.src = fall_right;
const damageLeftImg = new Image();
damageLeftImg.src = damage_left;
const damageRightImg = new Image();
damageRightImg.src = damage_right;
const deadLeftImg = new Image();
deadLeftImg.src = dead_left;
const deadRightImg = new Image();
deadRightImg.src = dead_right;

const bg1Img = new Image();
bg1Img.src = bg1;
const greenStoneTileImg = new Image();
greenStoneTileImg.src = greenStoneTile;

export const characterIdleLeft = [walk1LeftImg];
export const characterIdleRight = [walk1RightImg];
export const characterWalkingLeft = [walk1LeftImg, walk2LeftImg, walk3LeftImg, walk4LeftImg];
export const characterWalkingRight = [walk1RightImg, walk2RightImg, walk3RightImg, walk4RightImg];
export const characterWhipLeft = [whip1LeftImg, whip2LeftImg, whip3LeftImg];
export const characterWhipRight = [whip1RightImg, whip2RightImg, whip3RightImg];
export const characterJumpLeft = [jumpLeftImg];
export const characterJumpRight = [jumpRightImg];
export const characterFallLeft = [fallLeftImg];
export const characterFallRight = [fallRightImg];
export const characterDamageLeft = [damageLeftImg];
export const characterDamageRight = [damageRightImg];
export const characterDeadLeft = [deadLeftImg];
export const characterDeadRight = [deadRightImg];

export const environmentImgs = [greenStoneTileImg];

export const bgImgs = [bg1Img];
